dist: xenial

language: python

python:
  - 3.6
  - 3.7
  - 3.8-dev
  - nightly

install:
  - pip install --upgrade --upgrade-strategy eager pip setuptools
  - pip install --upgrade --upgrade-strategy eager .[test]

script: py.test --isort --flake8 --cov-report= --cov=unrest

after_success: coveralls

sudo: true
