language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - nightly
  #- pypy

install:
  - pip install --upgrade pip setuptools
  - pip install --upgrade .[test]

script: py.test --isort --flake8 --cov-report= --cov=unrest

after_success: coveralls

sudo: false
