[tool.black]
line-length = 79
skip-string-normalization = true
include = '\.py$'
exclude = '''
/(
    \.git
  | \.tox
  | \.venv
  | _build
  | build
)/
'''

[tool.isort]
multi_line_output=5

[tool.pytest.ini_options]
norecursedirs = ".git build *.egg-info .eggs venv"
flake8-ignore = "* W503 unrest/tests/static/openapi_result.py E501"

markers = [
  "flask",
  "http_server",
  "tornado",
  "sanic",
]
